# Generated by Django 4.2.13 on 2024-08-10 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='users',
            field=models.ManyToManyField(related_name='materia_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='classes',
            table='Materia',
        ),
        migrations.AlterModelTable(
            name='requisicion',
            table='Requisicion',
        ),
        migrations.AlterModelTable(
            name='semester',
            table='Semestre',
        ),
        migrations.AlterModelTable(
            name='users',
            table='Usuario',
        ),
        migrations.AlterModelTable(
            name='utensilios',
            table='Utensilio',
        ),
        migrations.CreateModel(
            name='Talleres',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.semester')),
                ('users', models.ManyToManyField(related_name='taller_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Taller',
            },
        ),
    ]
