# Generated by Django 4.2.13 on 2024-08-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_classes_users_alter_classes_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utensilios',
            name='solicitudes',
            field=models.IntegerField(default=0),
        ),
    ]
