# Generated by Django 4.2.13 on 2024-08-17 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_utensilios_solicitudes'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicion',
            name='taller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisiciones_taller', to='api.talleres'),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='asignatura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisiciones_asignatura', to='api.classes'),
        ),
    ]
