# Generated by Django 4.2.13 on 2024-08-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_requisicion_taller_alter_requisicion_asignatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='matricula',
            field=models.CharField(default='0', max_length=10, unique=True),
        ),
    ]
