# Generated by Django 4.2.13 on 2025-02-04 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_users_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisicionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('entregado', 'Entregado'), ('no_entregado', 'No Entregado'), ('danado', 'Dañado'), ('perdido', 'Perdido')], default='no_entregado', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('requisicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_estado', to='api.requisicion')),
            ],
            options={
                'db_table': 'RequisicionItem',
            },
        ),
        migrations.CreateModel(
            name='desechos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('litros', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desecho_taller', to='api.talleres')),
            ],
            options={
                'db_table': 'Desechos',
            },
        ),
    ]
